### ISSUE TITLE
不可避なビットコインの掲載

### ISSUE THREAD

**Issue by cryptophile-btc** [lostinbitcoin/categories#19]
Re: the above.
Would love to have my article 不可避なビットコイン (Medium, 2020) shared on your site.
Here is the link.

https://cryptophile-btc.medium.com/%E4%B8%8D%E5%8F%AF%E9%81%BF%E3%81%AA%E3%83%93%E3%83%83%E3%83%88%E3%82%B3%E3%82%A4%E3%83%B3-ee927070ae32

Best,
cryptophile

**Comment by lostinbitcoin** [comment]
Thank you for the suggestion. Happy to publish it on our site.
Please refer to [Wiki](https://github.com/lostinbitcoin/categories/wiki) for how to submit the article. 
Look forward to the pull request.
