### ISSUE TITLE
Fix Twitter link of a contributor: @cryptophile_btc

### ISSUE THREAD

**Issue by visvirial** [lostinbitcoin/categories#2]
**Describe the bug**
The twitter link on the bottom of the home page is wrong:

- ❌ https://twitter.com/cryptophile_btc/photo
- ⭕ https://twitter.com/cryptophile_btc

I tried to make a PR, but I couldn't find the md file for the home page.

**To Reproduce**
Nothing special.

**Expected behavior**
The link should not contain `/photo`.

**Screenshots**
Nothing.

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
Any

**Additional context**
Nothing.

**Comment by lostinbitcoin** [comment]
ありがとうございます🙏 リンク修正しました。
サイト自体はWordPressで作っていて、今のところ、記事や動画のPostのみGitHubで管理してます。ホームやその他のstaticページもオープンソース化して改善できたらとは思ってるので、方法論を調べてみます。もしよい方法ご存知でしたら教えてください。

**Comment by visvirial** [comment]
WordPress使わないで全部mdから生成するとか？
リンク修正確認できたのでクローズします。
