### ISSUE TITLE
ライセンスへの言及をしておいたほうが貢献しやすい

### ISSUE THREAD

**Issue by toshihr** [lostinbitcoin/categories#4]
**Is your feature request related to a problem? Please describe.**
コンテンツのライセンスがどうなっているかを明記しておくのがよいかと思います。
といいつつ、OSSだと制限の緩いMITライセンスだったりしますが、記事コンテンツだとどうするのがよいかはよく分からないです。

**Describe the solution you'd like**
一案は、
https://github.com/lnbook/lnbook/blob/develop/LICENSE.md
のようにCreative Commonsですかね。

**Comment by lostinbitcoin** [comment]
ロストインのコンテンツのライセンスですか？考えてなかったですが、オープンソースと言ってる以上、自由に使ってが筋な気がしますが、どうなんだろうか？
今のところ、オリジナルコンテンツは「歴史・記念日」くらいで、その他全て他人の著作物です。クリエイターとBitcoin Magazineなどの掲載媒体の許可は個別に取っていて、掲載にあたって相手が提示した条件にそって掲載しています。なので、誰かが勝手にコンテンツを条件に合わない形で二次利用されると問題になる可能性もあります。
とりあえず、原さんの挙げてくれたのをフッターに入れてみました。

**Comment by toshihr** [comment]
> なので、誰かが勝手にコンテンツを条件に合わない形で二次利用されると問題になる可能性もあります。

とすると、全部をCCとするのはよくないですよね。Creative Commonsが適用されるのは〇〇のページだけで、その他は転載厳禁、とかと明記なのかな。

**Comment by lostinbitcoin** [comment]
社内でも議題に上げたらCCだと問題あるとのことなので、削除しました。改めて利用規約のページを作ることになると思います。ライセンスについては全く頭になかったので、指摘していただいて助かりました。ありがとうがいました。
