### ISSUE TITLE
このサイトの正式名が記載されていない？あるいは、よくわからない。

### ISSUE THREAD

**Issue by toshihr** [lostinbitcoin/categories#6]
**Describe the bug**
このサイトの正式名が記載されていない？あるいは、よくわからない。

- ブックマークをすると「ロストイン・ビットコイン」となる
- ページ内では「迷宮ビットコインの歩き方」と言及している

といったかんじになってますね。
「迷宮ビットコイン」が正式名ですか？

**Comment by lostinbitcoin** [comment]
WPの設定では、タイトルが「ロストイン・ビットコイン」で、タグラインが「迷宮ビットコインの歩き方」です。ロストインって日本語として通じるかわからなかったのと、ちょっと前まで別のドメインネームを考えていたのもあって、サイトに記載してなかった。でもロストインで通じるみたいなので、「迷宮ビットコインの歩き方」の上に入れました。

**Comment by toshihr** [comment]
例えばTwitterなどでこのサイトを紹介する場合は、「ロストイン・ビットコイン」が正しいということですね。
どこかページ内の見えるところにあるといいですね。

**Comment by lostinbitcoin** [comment]
どっちでも良いと思ってます。「ロストイン・ビットコイン」はドメイン名ということもありタイトルにしましたが、「迷宮ビットコインの歩き方」の方がサイト趣旨がわかりやすいと思うので。
OPGでしたっけ？SNSでシェアした時にタイトル、タグライン、ヒーローイメージ付きプレビューが出るように、プラグインで設定したのですが反映されてませんね。違うプラグインを探してみます。
