### ISSUE TITLE
サイト下部に、テンプレート文字列が残っている

### ISSUE THREAD

**Issue by toshihr** [lostinbitcoin/categories#7]
**Describe the bug**
<img width="1269" alt="スクリーンショット 2022-05-29 19 01 09" src="https://user-images.githubusercontent.com/6064065/170862544-687ce5be-81e7-450c-973b-73f08381dc49.png">

こちらの「Neve | Powered by WordPress」は消しちゃって良い気がしますね。

**Comment by lostinbitcoin** [comment]
無料のthemeを使ってるので、消せないと思い込んでたけど消せました。ありがとうございました。

**Comment by toshihr** [comment]
Closeします
