### ISSUE TITLE
「ビットコインの入手方法」のページでリンク先の記事のタイトルが重複

### ISSUE THREAD

**Issue by akipponn** [lostinbitcoin/categories#92]
**Describe the bug**
「ビットコインの入手方法」のページでリンク先の記事のタイトルが重複して表示されています。
https://lostinbitcoin.jp/category/how-to/exchange/

以下のスクリーンショットのように、「AndGoさんの「つみたてとこ」で簡単、お得にビットコイン積立」「STACK SATS Bitcoin」へのリンクが複数回表示されています。

![スクリーンショット 2023-07-20 8 25 07](https://github.com/lostinbitcoin/categories/assets/170129/3cd1cad6-4f35-4c4b-b1c4-ebef7e6cf6f2)

**To Reproduce**
1. Go to '[ビットコインの入手方法](https://lostinbitcoin.jp/category/how-to/exchange/)'

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave browser 1.152.130, Safari 15.6.1.

**Comment by lostinbitcoin** [comment]
ご報告ありがとうございました。
